### ISSUE TITLE
Re-write how the server sends Discord event data

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#1009]
For the competition Discord announcements, the server sends group id separately from the competition itself. After API v2, this is not needed anymore because Competition contains the group id. This should be re-written from
```
dispatch('COMPETITION_CREATED', {
    groupId: competition.groupId,
    competition
  });
```
to just
`dispatch('COMPETITION_CREATED', competition);`

This file is where the changes need to be made: [discord.service.ts](https://github.com/wise-old-man/wise-old-man/blob/5f31b75a579a14148d12b5a433b636c698f4a62a/server/src/api/services/external/discord.service.ts#L113)

These changes need to be done at the same time as changes on the Discord bot are made to handle new data.

**Comment by psikoi** [comment]
Technically the `groupId` field is not strictly necessary because it is also repeated inside the `competition` object. But it's not a big deal to keep it just to keep it consistent with other events 🤷 

I'm fine with the extra bytes in exchange for consistency, closing.
