### ISSUE TITLE
Change Doctor icon to current ingame design

### ISSUE THREAD

**Issue by Jakesterwars** [wise-old-man/wise-old-man#1033]
Just a personal reminder. They changed it from Red to White for the Geneva Convention issue.

**Comment by aleccaputo** [comment]
Is the proposal to change this
https://github.com/wise-old-man/wise-old-man/blob/master/app/public/img/runescape/roles/Doctor.png
To the white cross: this https://oldschool.runescape.wiki/w/File:Clan_icon_-_Doctor.png

**Comment by psikoi** [comment]
that sounds right yea

**Comment by Jakesterwars** [comment]
@aleccaputo Yes that is correct.

**Comment by aleccaputo** [comment]
on it
