### ISSUE TITLE
Get Player Snapshots endpoint missing ehb and ehp 

### ISSUE THREAD

**Issue by Jonxslays** [wise-old-man/wise-old-man#1063]
## Summary

When making a request to `/players/{username}/snapshots`, the Snapshot Data Values object returned inside the Snapshot by the API is incomplete. 

## Reproduction steps

- Make a request to https://api.wiseoldman.net/v2/players/zezima/snapshots?period=day
- Note the fields returned with all bosses
- Note the fields returned with all skills

## Expected behavior

The Snapshot Data Values will contain all documented fields.

## Actual behavior

All skills are missing the `ehp` field, and all bosses are missing the `ehb` field.

**Comment by Jonxslays** [comment]
Unsure if this is related, but hitting the Get Name Change Details endpoint at `/names/{id}` also excludes `ehb` and `ehp` from the old and new stats fields.

Additionally `id` is excluded from the new stats on id=170096, as well as no Name Change Data whatsover on id=170098

**Comment by psikoi** [comment]
> Additionally id is excluded from the new stats on id=170096, as well as no Name Change Data whatsover on id=170098
We do not include that data for resolved name changes (approved/denied). I guess the issue here is that it should be marked as nullable on the docs (with a note explaining why)
