### ISSUE TITLE
Editing a team competition using the web UI deletes all participants

### ISSUE THREAD

**Issue by Septem151** [wise-old-man/wise-old-man#1087]
When modifying a competition, for example changing the title of the competition, changing the competition metric, or renaming teams, every participant is removed.

Steps to reproduce:
- Create a Competition with teams using the Web UI
- Try to then edit that competition using the Web UI
- All participants are deleted

This is related to https://github.com/wise-old-man/wise-old-man/issues/1077 in which it's stated there was a fix merged in https://github.com/wise-old-man/wise-old-man/pull/1078 but this is still not the case, as I'm experiencing this issue.

**Comment by psikoi** [comment]
That's not good at all, looking into it right now. I'll follow up with a fix

**Comment by psikoi** [comment]
This doesn't seem to be happening with regular classic competitions, will try with team competitions.

**Comment by Septem151** [comment]
> Thanks for the heads up, the fix should be live in 3-4mins

Thanks for the amazing response time!
