### ISSUE TITLE
Remember most recent period selection

### ISSUE THREAD

**Issue by Aluminoti** [wise-old-man/wise-old-man#1098]
![image](https://user-images.githubusercontent.com/77535556/223158354-dff58565-4c25-4d34-b312-53bd39b95994.png)

Examples:

1)
- Go to a players gained page
- Select the period dropdown
- Select a custom period, for this example we can select values 01 Jan 2023 00:00 and 01 Mar 2023 00:00, and click confirm
- Select the period dropdown again
- Select custom period (the custom range defaults to the current date and time minus 1 week)
* I would expect to see the previously selected custom period populated -> 01 Jan 2023 00:00 and 01 Mar 2023 00:00

2)
- Go to a players gained page
- Select the period dropdown
- Select any period, for this example we will select "Day"
- Select the period dropdown again
- Select custom period and cancel (this sets the period dropdown to "Week" regardless of what period was selected previously)
* I would expect to see the period dropdown being retained as "Day" since it was the most recent selection/change

**Comment by psikoi** [comment]
Those two use cases you described are fixed in the beta app (soon to be promoted out of beta).
https://beta.wiseoldman.net/

 Closing.
