### ISSUE TITLE
Request: PLEASE fix the "Day" XP gained. No idea what timezone it goes by, but anytime I use it, most times it says, "No XP Gained"

### ISSUE THREAD

**Issue by GitHubQueenn** [wise-old-man/wise-old-man#1109]
Please allow us to set the time zone at which time it starts tracking XP for "Day," preferably at 12 midnight, or at least set it to 24-hr period. This happens in Discord when I use "/gained period:Day"

**Comment by psikoi** [comment]
Discussed on GitHub, that is not how exp trackers work, unlikely we'll ever implement fixed time periods, closing.
