### ISSUE TITLE
Some role icons don't show up

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#1170]
One example is Gnome Child.
It tries to load the file `Gnome child.png` instead of `Gnome Child.png`. This is because the capitalize function is only capitalizing the first letter in the name, not every first letter in every word. 

https://github.com/wise-old-man/wise-old-man/blob/ff2726f717a18125c868944d6d72a312d8339ed0/app/src/utils/strings.js#L1

It makes the `getRoleTypeIcon` function return the wrong file name.
https://github.com/wise-old-man/wise-old-man/blob/ff2726f717a18125c868944d6d72a312d8339ed0/app/src/utils/player.js#L41

**Comment by psikoi** [comment]
Fixed by #1167 and #1171
