### ISSUE TITLE
Efficiency Leaderboard is capped to 20

### ISSUE THREAD

**Issue by devenini** [wise-old-man/wise-old-man#1249]
In the beta version, we cannot browse the [Efficiency leaderboard](https://beta.wiseoldman.net/leaderboards/efficiency) beyond the first 20 entries. The previous version had a "load more" feature when you reached the bottom of the page.

Perhaps adding pagination would improve the user experience. Pagination would allow users to skip and browse the leaderboard quicker and more easily. 

Thoughts?

**Comment by psikoi** [comment]
Yeah that's true, we should re-add that
