### ISSUE TITLE
EHP

### ISSUE THREAD

**Issue by dekvall** [wise-old-man/wise-old-man#125]
There have been some talks lately about EHP. I would for it to be two EHP measures, EHP and LEHP.

__EHP__
Your Efficient Hours Played based on current EHP rates. Rates would be determined by prominent actors of the HLC.

__LEHP__
Legacy EHP, your efficient hours played but calculated with the rates that existed when you gained your xp. This way you will never lose LEHP when a new faster method is found and rates change. Saving historical EHP would also give us an idea of how rates have changed over time.

The implementation needs to be scalable as special EHP rates based on account type most likely will be added too. 

It has been suggested to place all rate information in a separate repo, so that it will be easy to discuss and pr changes for people not very well versed with vc. Also, this makes it so they don't need to clone the entire codebase for a simple rate change.

It's probably best to calculate EHP the current EHP on player update and store it on the snapshot. This would make it possible to use the same method as we do for xp when calculating the  daily/weekyl/monthly/yearly deltas if rates haven't changed in a given period. But it might be ok anyways since if rates do change, you have actaully lost EHP over the given period.

LEHP is a bit more complicated to implement. It would require us to calculate the experience gained between two snapshots, calculate the EHP of that and store it somewhere else to avoid going through every snapshot every time the player page is loaded. It would, however be easiest to store it like this so it might be worth figuring out the impact that this has on the system. Another alternative would be to store the accumulated LEHP somewhere else like we do with initialValues, but the accumulated data would be stored as daily/weekly/monthly/yearly fields. If a player updates we add to all fields and whenever a snapshot times out we subtract that delta EHP from the field. I am not sure how easy timing out snapshots would be.

It feels like all this is pretty doable, at least the regular EHP if we get the correct rates.

**Comment by psikoi** [comment]
> This way you will never lose EHP when a new faster method is found 
I'd change it to LEHP

**Comment by SomeZer0** [comment]
Would EHP be calculated differently for Reg/IM/UIM?

**Comment by psikoi** [comment]
Yes, you'd have EHP and Special EHP (tied to your account type)

**Comment by psikoi** [comment]
Changing to low priority until @dekvall comes back

**Comment by psikoi** [comment]
We have figured out the algorithm to EHP and TTM and development on this will start soon.

I'd like to use this space to discuss expected features that might use these variables.

- TTM calculation
- EHP/EHB calculation
- EHP/EHB competitions
- Store EHP and EHB (and ranks) in snapshots
- EHP/EHB deltas
- EHB/EHB records
- Add TTM and EHP to a player's details
- Virtual Hiscores (EHP/EHB leaderboards)


PS: I don't know if EHP/EHB achievements should be a thing since those values can(?) decrease overtime.
