### ISSUE TITLE
Fetch datapoints for all competitors on competition start

### ISSUE THREAD

**Issue by dekvall** [wise-old-man/wise-old-man#126]
It's easy to forget.

**Comment by psikoi** [comment]
The issue with this is, we could setup a scheduled job to fetch all on comp start, but if someone edits the start date later, we'd have to setup another scheduled job, and idk how we'd cancel the previous one

**Comment by dekvall** [comment]
I don't think we neccesarily need to cancel it? It would just give players an extra datapoint.

**Comment by psikoi** [comment]
Hiscores fetches are our currency for this project, the less we use, the better. But for now I think that's okay. Do you wanna work on this? It's similar to the update all you already worked on. Except it uses `jobs.schedule` instead of `jobs.add`
