### ISSUE TITLE
Beta opt-in persistence in cookie or LocalStorage

### ISSUE THREAD

**Issue by nibsitaas** [wise-old-man/wise-old-man#1274]
I don't know how long the beta period is, but I think it would be nice to be forwarded straight to `beta` when I visit the front page, if I opt in. Kind of like how Reddit does the old reddit opt-in redirect.

**Comment by psikoi** [comment]
Good news! I think the beta will be promoted to the "live" version this sometime this week.

it's a bit too late for me to spend time on this but it would have been a good idea to implement a month or two ago!

**Comment by nibsitaas** [comment]
Nice! Loving the project so far. I had something like this under works a few years ago, but I figured I might give it a shot with mobile apps using the WOM API instead.
