### ISSUE TITLE
[docs] efficiency/leaderboard docs are missing offset and limit query params

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#1388]
The `GET /efficiency/leaderboard` endpoint in the documentation is missing offset and limit query params. Should be added in [efficiency-endpoints.mdx](https://github.com/wise-old-man/wise-old-man/blob/75014d9eeed5492aadc58a9da965b2bde633748c/docs/docs/efficiency-api/efficiency-endpoints.mdx).

**Comment by psikoi** [comment]
Fixed by #1399
