### ISSUE TITLE
Retain Account Type between selection of efficiency rates page

### ISSUE THREAD

**Issue by Miconen** [wise-old-man/wise-old-man#1396]
Currently switching between EHP <-> EHB tabs resets the `Account Type` selection to `Main`. Changing between tabs should keep the selected `Account Type`.

`https://www.wiseoldman.net/ehp/ironman`
![image](https://github.com/wise-old-man/wise-old-man/assets/9155442/95abd4e9-73f5-499e-8a70-303914a90228)

`https://www.wiseoldman.net/ehb/main`
![image](https://github.com/wise-old-man/wise-old-man/assets/9155442/0f31c190-4af9-4693-870a-6b85dcb4d2cf)

**Comment by psikoi** [comment]
Fixed by #1400
