### ISSUE TITLE
Allow Competition APIs to be used with womIds

### ISSUE THREAD

**Issue by Trottero** [wise-old-man/wise-old-man#1438]
Currently the competition API's require usernames to create or update teams. This works great for the website where users are expected to search, and add the player that way. 3rd party services however, would probably prefer to store wom's internal player id as the users name is not stable.

This however means that currently 3rd party services have to request the players username for every mutation they intend on doing, leading to extra API calls (a lot of them if this competition is not bound to a group).

My proposal is to add a new set of endpoints (or maybe an extra field in the request body?) So that IDs can be passed instead of names.

**Comment by psikoi** [comment]
I think it's best if third party services use usernames as the player identifiers instead of player IDs.

What's your use case? Why are you using player IDs, and how?

**Comment by psikoi** [comment]
We continued this conversation on discord (https://discord.com/channels/679454777708380161/696219254076342312/1209863709955194910) and I don't think the value outweighs the added complexity, closing.
