### ISSUE TITLE
[app] Show previous role in group activity

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#1451]
The idea is to show the data like we show other data on hover in other places on the site. We can't really show the previous role directly in the recent activity list without some big UI changes unfortunately. The UI code needs to properly handle old role changed activities where previousRole is null.
![image](https://github.com/wise-old-man/wise-old-man/assets/5983417/20a63fa7-87a9-4128-a4b6-140e85364414)

This requires the changes outlined in #1450

**Comment by aleccaputo** [comment]
Per my last PR #1450 i only added previousRole to various memberActivites but not on the member themselves.
Should the previous role only show up when you hover over a member in the "recent activity" or should it also show up when hovering a member in the "members" table as well?

**Comment by psikoi** [comment]
It should only be shown on a hover panel on the members activity section
