### ISSUE TITLE
JS-Client defining type: module while exporting only CJS

### ISSUE THREAD

**Issue by aleccaputo** [wise-old-man/wise-old-man#1459]
![image](https://github.com/wise-old-man/wise-old-man/assets/19272595/0352cfe6-b15f-47ca-8efe-63adaabc84b3)

Noticed this when installing the latest `@wise-old-man/utils`. It's because the `package.json` defines `type: module` which implies the resulting bundled code is ESM compliant.

There are two fixes here:
1. The easy one is to just remove that type declaration in `package.json` (or rename the bundle to `.cjs`)
But ESM is cool and good so....
2. We could have another build step that outputs both a commonJS bundle AND and ESM bundle.

Here's an example of someone doing it adding the required `exports` flag to `package.json`:
https://dev.to/mbarzeev/hybrid-npm-package-through-typescript-compiler-tsc-150c

**Comment by psikoi** [comment]
Is this something you could contribute to @aleccaputo ?

**Comment by aleccaputo** [comment]
@psikoi for sure.
Do you think i should just remove the module declaration for now and make a separate PR for exporting both builds?

**Comment by psikoi** [comment]
> @psikoi for sure. Do you think i should just remove the module declaration for now and make a separate PR for exporting both builds?

yea that sounds like a good plan

**Comment by psikoi** [comment]
Fixed in #1461
