### ISSUE TITLE
My group iron is considered a "regular" account

### ISSUE THREAD

**Issue by calebmchenry** [wise-old-man/wise-old-man#1478]
Rsn: Clearly bald

My group ironman is being tracked as a regular account.

Steps to reproduce:
1. https://wiseoldman.net/players/Clearly%20bald
2. Click horizontal 3 dots
3. Check player type...

A notification is presented "No change: Clearly bald is still Regular"

Same applies for my group mates
https://wiseoldman.net/players/bongo%20ninja
https://wiseoldman.net/players/FaultyRobot

**Comment by psikoi** [comment]
The hiscores classify GIM as regular accounts, there is no "GIM player" hiscores. If we can't search your name on the GIM hiscores and see your stats, we can't know if you're GIM. So by default, GIM are seen as regular accounts on WOM.

It has been discussed quite a bit on our Discord in the past, and it would take a considerable amount of work to properly classify all GIM as GIM on WOM.

We would have to browse through about 6.5k pages of the GIM hiscores to find group names, and then individually browse each group's page (130k pages) to read the names of the players included in them.

Unfortunately that doesn't seem worth the time investment and resources, especially as GIM is growing less and less popular everyday.

**Comment by JLucas98** [comment]
(Tried to find this on discord, but didn't see it) Would it not be possible to have it be an opt-in thing where a GIM that wants to be counted as such can give you [their group link](https://secure.runescape.com/m=hiscore_oldschool_ironman/a=13/group-ironman/view-group?name=group%20squad)? Then you don't have to crawl literally every group, you could just match their user against those in the team
