### ISSUE TITLE
Unable to close verification code modal when editing a group

### ISSUE THREAD

**Issue by Jonxslays** [wise-old-man/wise-old-man#1498]
Reproduced with Chrome and Firefox on Linux desktop. 

### Repro steps

- Navigate to any group page
- Click the 3 dots next to Update all
- Click Edit

### Expected results

I can hit `esc` or click an X in the top right of the modal to close it.

### Actual results

The only way to get rid of the modal is to navigate away from the page.

**Comment by psikoi** [comment]
that's not really a bug, although my approach might be flawed.

The idea is that you cannot just dismiss that dialog and continue editing because the verification code is required. Maybe we should add a "Go back" option to the dialog, in case people want to go back to the group's page.

**Comment by Jonxslays** [comment]
Yeah, it just felt counterintuitive. I think that would be a good solution.

**Comment by psikoi** [comment]
Fixed in https://github.com/wise-old-man/wise-old-man/pull/1506
