### ISSUE TITLE
Search icon display

### ISSUE THREAD

**Issue by Jakesterwars** [wise-old-man/wise-old-man#156]
On Discord there was a suggestion to make the search icon on the search bars a clickable entity. With debate we have options that were brought up and we just need to decide on which would be preferred.

1. Make the icon a button and remain where it's at.
2. Section off the icon in the search bar and make it a button still.
3. Move the icon out of the search bar and attach a button up against the search bar with it.
3. Prepend the icon in the search bar without making it a button.
4. Remove the icon entirely.

These were the ones brought up and there can be more styles that people can bring up if they want.

**Comment by Jakesterwars** [comment]
To actually bring up my choice is number 2 or number 3. The icon itself brings a visual key outside of the placeholder text. If my options are enjoyed, I would prefer 4 then.

**Comment by psikoi** [comment]
`Section off the icon in the search bar and make it a button still.` what does this mean?

**Comment by Jakesterwars** [comment]
https://cdn.discordapp.com/attachments/696219233167736884/714550438262865980/unknown.png Something similar to this, but obviously a full bar not the half bar.

**Comment by psikoi** [comment]
I vote any but 3

**Comment by dekvall** [comment]
I think it should be kept as-is.

**Comment by psikoi** [comment]
Are there any downsides to just making the icon clickable? people who don't click it wouldn't notice it, and people who do, would get the desired result?

**Comment by Jakesterwars** [comment]
There's no downsides, it's just not a normal practice to do it that way.

**Comment by psikoi** [comment]
I'm fine with anything besides making it a separate button

**Comment by breeku** [comment]
I too think it's fine as-is, if it has to be clickable i'd prefer to just make the icon clickable

**Comment by psikoi** [comment]
Yea, let's just make the icon clickable 😆

**Comment by psikoi** [comment]
I went it 5, because meh, the icon isn't adding much context since the placeholder text already contains "Search"
