### ISSUE TITLE
Top Right "Country" Box

### ISSUE THREAD

**Issue by Nick2bad4u** [wise-old-man/wise-old-man#1574]
![image](https://github.com/user-attachments/assets/fc564125-e66b-445c-ad06-e6af57ead398)

How do I set the Country?

**Comment by StephanBijzitter** [comment]
In discord: https://discord.com/channels/679454777708380161/802680940835897384

**Comment by rorro** [comment]
https://github.com/wise-old-man/wise-old-man/wiki/User-Guide:-How-to-setup-countries-flags

If you have further questions about it, feel free to ask on Discord.
