### ISSUE TITLE
Bossing records show -1 kills and rank for when 0 KC or unranked

### ISSUE THREAD

**Issue by hjdarnel** [wise-old-man/wise-old-man#171]
![image](https://user-images.githubusercontent.com/7868899/83434035-5c5fed80-a3ff-11ea-8374-f4a243bd0d2f.png)

This is probably a pretty simple backend fix. The frontend request `/api/snapshots/?playerId=1758` also shows -1 for these bosses 
![image](https://user-images.githubusercontent.com/7868899/83434212-a5b03d00-a3ff-11ea-88c5-a11d7ec3fce0.png)

**Comment by Jakesterwars** [comment]
If you don't have enough of the kills for the hiscores to track you, they show up as -1 on the list. I think this was brought up before in Discord about changing that to 0, but I can't recall the outcome.

**Comment by psikoi** [comment]
All bosses have a minimum kc to be on the hiscores now, they are 50, 10 or 2 depending on the boss, anything below that is "-1" on the hiscores API.

So -1 to us is untracked, we could however show 0 on the frontend to avoid confusion, but as the API goes, I believe it's best to keep it at -1, to differentiate from 0 kc.

**Comment by psikoi** [comment]
@Jakesterwars on discord:

> Wonder if it should be changed to 0 and then a hover tooltip is added to them for the criteria to be tracked.

**Comment by Knutakir** [comment]
I think showing `0` can be misleading and make the user think it's actually `0` even if it's in the interval `0` - `50` or showing tooltip on hover. Another possibility could be displaying `-`.
Also, this relates to skills and activities not being on the HiScores as well.

**Comment by psikoi** [comment]
Maybe displaying `< 50`?

**Comment by odevine** [comment]
I think <50 is the way to go here, it's much clearer than saying 0 and removes the need to have a tooltip
