### ISSUE TITLE
TypeScript conversion - Server

### ISSUE THREAD

**Issue by Jakesterwars** [wise-old-man/wise-old-man#190]
To have tracking for this as a whole, this will be the issue related to the server conversion to TypeScript as a whole. There will be a separate one for the App itself to move to TSX.

**Comment by Jakesterwars** [comment]
Currently standing is that sequelize requires a bit of a "refactor" to work in TypeScript with our current design. This is going to take a bulk of the time for this PR because we need to make sure it does not break any functionality the models are hooked up to.

**Comment by psikoi** [comment]
The first stage of this has been merged. 

The second stage should be actually adding types to everything, restricting the amount of "anys" we use.

**Comment by psikoi** [comment]
I think this can be closed now, as #410 improved typings even further.
