### ISSUE TITLE
Using enter, arrow & escape keys on search field

### ISSUE THREAD

**Issue by MathieuDR** [wise-old-man/wise-old-man#223]
A few suggestions to make the search field more accessible and keyboard-friendly

- Escape should "Cancel" the search
- Arrow keys should iterate through the list of results ( a kind of hover effect)
- Enter should select the first, or selected item with the arrow keys.

Doing this will completely make the search field usable through the keyboard.

Kind of related to #193

**Comment by Jakesterwars** [comment]
Points 2 and 3 seem to work already. Point 1 just needs a key capture in AutoSuggestInput.

**Comment by psikoi** [comment]
Points 2 and 3 only work for the `AutoSuggestInput` component, but not for the `Selector` (with search) component

**Comment by psikoi** [comment]
Added in the new beta website https://beta.wiseoldman.net/

I'll consider it done as it'll eventually be live in production. Closing.
