### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#314]
From Boom on Discord:

![image](https://user-images.githubusercontent.com/3278148/87243079-cc17be00-c42a-11ea-8b30-9b5b801ec0f5.png)

**Comment by aar9nk** [comment]
I don't understand which word is typed incorrectly?

**Comment by psikoi** [comment]
the `'s` mixed with `is`, if I remember correctly. 🤔

**Comment by psikoi** [comment]
Free shirt right here

**Comment by apstone** [comment]
@psikoi I am having trouble finding this error text.. would this be sufficient or can you help me find this text?
```
    case ASSERT_TYPE_FAILURE: {
      const notification = {
        text: `Failed to reassign player type. ${action.displayName} is already ${action.playerType}.`,
        type: 'error'
      };

      store.dispatch(showNotification({ ...notification }));
      break;
    }
```

**Comment by psikoi** [comment]
I guess this is no longer an issue, couldn't find this error message anymore. And also it seems that endpoint no longer returns an error if the account type hasn't changed. Apologies.
