### ISSUE TITLE
Unranked users in a competition show negative at the end if still unranked

### ISSUE THREAD

**Issue by Jakesterwars** [wise-old-man/wise-old-man#324]
https://cdn.discordapp.com/attachments/696219233167736884/732291110818545724/unknown.png

via Joe 7
`Good afternoon, on skill competitions if a player isn't ranked on the hiscores the end xp is showing -1 instead of 0. Not a major problem but I get questioned a lot how someone could have negative XP`

**Comment by psikoi** [comment]
Fixed in #386
