### ISSUE TITLE
Player gains for custom time period

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#390]
From `Boom` on Discord:

> It would be great if clicking someone's name on a competition page showed that player's overall gains for the duration of the competition. 
> Temple and cml both have this, whereas wom just takes you to their profile.

This would require:
- Adding new "startDate" and "endDate" params to the /players/{id}/gained endpoint/service
- Adding new url params to the player page that would then be used in the http request

**Comment by Koenic** [comment]
Please also make this work for groups so we can check for inactivity in clans.
