### ISSUE TITLE
Capitalization on charts

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#400]
Not a big deal, but usernames on progress charts in competitions aren't being capitalized the same way they are elsewhere.

![Screenshot_46](https://user-images.githubusercontent.com/66145237/93306569-4cf18e00-f7bd-11ea-9e1d-f25caab8a2f8.png)
![Screenshot_45](https://user-images.githubusercontent.com/66145237/93306576-4e22bb00-f7bd-11ea-927e-8c038ef9fd42.png)

**Comment by psikoi** [comment]
Solution:

https://github.com/wise-old-man/wise-old-man/blob/master/app/src/redux/selectors/competitions.js

line 69

`label: participant.username`

"username" needs to be "displayName"

**Comment by apstone** [comment]
Can I take this one? @psikoi

**Comment by psikoi** [comment]
Yep
