### ISSUE TITLE
More Overall XP achievements

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#423]
Currently, the lowest achievement for overall xp on WOM is 500m. I think more achievements should be added to help encourage and excite lower levels (100m, and 50m at least).

My main idea for deciding what to consider an achievement is using the vanilla client's xp tracker. You can set xp goals for your account. That screen looks like this:

![Screenshot_48](https://user-images.githubusercontent.com/66145237/96405926-9279f000-119b-11eb-9b24-1ed24d8125d5.png)

The "End Points" (for overall xp) is actually auto-filled and can't be changed, implying that the number is an important and noteworthy milestone. I know there is also a milestone at 50m, and obviously at 100m. I'm sure there are some higher and lower, though I'm not sure what they are. Some may not be worthy of an achievement, but I think it's worth a discussion. I think these xp milestones would make good achievements for WOM.

**Comment by psikoi** [comment]
Sounds good to me, it would also be good to have a few more "overall" achievements, like:

- 70 base stats
- 80 base stats
- 90 base stats

**Comment by psikoi** [comment]
A note for development:

Currently, whenever a player updates, we check if any of the achievements have now been achieved, and whenever a player imports their CML history, we do a re-evaluation of previous achievements (to improve achieved date accuracy).

If we simply add new "lower" achievements, their achieved dates will be "today", even though the player should have had those achievements months/years ago.

To correctly implement new achievements, we need to also re-evaluate everyone's achievements post-merge, to get correct dates.
