### ISSUE TITLE
Duplicated CSS for modals

### ISSUE THREAD

**Issue by lukaszklis** [wise-old-man/wise-old-man#467]
When working on #465, I've realised we're duplicating a lot of SCSS code for modals. Since I've heard @psikoi has been working on refactoring the front-end architecture, I wanted to check whether the issue mentioned would be in scope of those changes.

My suggestion would be to introduce a common component `Modal` where basic styling + props would be passed alongside with `children` to be rendered within the modal.

**Comment by psikoi** [comment]
There's a new beta website being built with tailwind, no more duplicated stylesheets.
https://beta.wiseoldman.net/

I'll consider it done as it'll eventually be live in production. Closing.
