### ISSUE TITLE
Achievement orb shows "Invalid date" for not not achieved items

### ISSUE THREAD

**Issue by lukaszklis** [wise-old-man/wise-old-man#475]
**Steps to reproduce:**

1. Navigate to tracker user profile.
1. Click on the "Achivements" tab.
1. Hover over any achievement orb which has not been achieved yet.
1. Text "ACHIEVEMENT_NAME- Invalid date" is shown.

**Expected behaviour:**

Display text informing this achievement orb has not been achieved yet (suggestion: "ACHIEVEMENT_NAME - goal not reached yet")

**Comment by psikoi** [comment]
Notes to anyone looking to fix this:

You can use the `isCompleted` variable to differentiate between a unachieved achievement, and a unknown date achievement.
