### ISSUE TITLE
Quick group competition creation

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#476]
Suggestion:

Add an option to start a new group competition from the group's page. This would take you to the "New competition" screen, with the group's name auto-filled. You would still need a passcode to save the competition.

Two options I had in mind would be:
a) Beginning or end of the competition list
![Screenshot_105](https://user-images.githubusercontent.com/66145237/99162240-c8d25e80-26b8-11eb-8b4e-f2aff8c9b9ff.png)

b) In the group edit menu:
![Screenshot_106](https://user-images.githubusercontent.com/66145237/99162243-d5ef4d80-26b8-11eb-925a-01c3268d5aaf.png)

**Comment by Jakesterwars** [comment]
I'm looking into it. Just figuring out a way to handle data being passed on router.push in the app.

**Comment by Jakesterwars** [comment]
Currently the button I have put is in option 2.

![image](https://user-images.githubusercontent.com/27702288/99177901-8cf8c280-26d3-11eb-8af1-ef0aebd79561.png)

In the router.push I pass in state props and set the Competition state values as needed on render.
