### ISSUE TITLE
Add point amounts to /league/tiers API endpoint

### ISSUE THREAD

**Issue by Nightfirecat** [wise-old-man/wise-old-man#481]
Currently, the API response is of the following format:

```json
[
	{
		"name": "bronze",
		"threshold": 250900
	},
	// ...
]
```

It would be helpful for these lookups to have another field (`points` perhaps?) which shows the number of league points needed to attain that rank threshold.

**Comment by psikoi** [comment]
Sounds good, shouldn't be too hard 👍

**Comment by psikoi** [comment]
League ending soon, the hiscores don't like scraping anymore, this would 6x the amount of pages scraped. Might aswell close and forget about it.
