### ISSUE TITLE
Fix User Search for existing users

### ISSUE THREAD

**Issue by Astrect** [wise-old-man/wise-old-man#497]
Currently upon visiting the /search/players/{username} page, you will still see the message "Username is not tracked", even though any names matching are found in a search column below. 

![Image of Yaktocat](https://i.imgur.com/dZBb33X.png)

**Comment by psikoi** [comment]
It seems this player loads the search results after doing the first render, so it incorrectly shows that it could not have been found.

This should be a two part fix:

- While fetching the search results, render "Searching..." instead
- If one of the results is a perfect match (ignoring capitalization and special chars) to the searched username, redirect to the player page directly
