### ISSUE TITLE
Compacted User Gains

### ISSUE THREAD

**Issue by Astrect** [wise-old-man/wise-old-man#499]
Offer an alternate table view that shows "compacted" user gains, or update the existing table to display compacted gains by default.

![Image of Updated Table](https://i.imgur.com/aOwnVj1.png)

**Comment by Jakesterwars** [comment]
I'm assuming this is for the overview table for the updated one? If so, the compacted values would be just pulled from the gained details?

**Comment by Astrect** [comment]
> I'm assuming this is for the overview table for the updated one? If so, the compacted values would be just pulled from the gained details?

It would be on whichever table @psikoi determines it should go on. Personally I suggest removing the need for both a "deltas" and "details" table and combine it all into 1 table, that would clean things up and be a bit more on par with other trackers.

**Comment by psikoi** [comment]
I did some experiments with this and it really doesn't fit with the current table width. We'd have to change the layout of the overview page, and that doesn't seem to be happening anytime soon. Closing for now.
