### ISSUE TITLE
[Discussion] Discord Bot

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#50]
It would be great to have a discord bot, geared towards clans.

Some of the obvious features would be:

- Player gains checking Ex: `!gains week Psikoi`
- Competition status checking Ex: `!competition status 1354` (Would say like 6 hours 23 minutes left)
- Competition top 5 (or 10 or whatever)  Ex: `!competition top 1354`

Also, it would be nice if a player could associate a WOM player to their discord, like
`!link Psikoi`, so whenever the bot referred to him, it would actually tag.

And in the same fashion, associate a WOM group, to a discord server, which would then announce any group related news, such as:

- Announce (on the clan's discord) new group competitions
- Announce member achievements (Ex: Psikoi is now maxed total!)
- Announce top 3 changes in any group competition (Ex: Zulu just smoked Psikoi and is now rank 1 on the woodcutting competition)

**Comment by rui-martins** [comment]
### Ideas for commands and notifications

_**Commands:**_

`!setgroup [groupId]` : The bot now only tracks certain group from wiseoldman
`!setplayer [playerId]` : Add single players to track
`!removegroup [groupId]` : Removes a group being tracked by the bot
`!removeplayer [playerId]` : Removes a player being tracked by the bot
`!clear` : Removes all entities being tracked by the bot
`!setchannel [channelName]` : Set the channel which the bot writes in
`!removechannel` : Removes the channel bot is writing to
`!help` : A list of commands for the bot usage
`!setlang [string]` : Example: `!setlang PT` This way the server only sends daily notifications
upon reaching midnight in that specific country

**_Notifications:_**

- Daily most EXP gained:
Bot notifies a disc channel with the name of the player that gained the most exp that day

- Weekly most EXP gained:
Bot notifies a disc channel with the name of the player that gained the most exp that week

- Monthly most EXP gained:
Bot notifies a disc channel with the name of the player that gained the most exp that month

- 99s Notifier:
Bot notifies a disc channel when one of its members reaches a 99

- Maxed Notifier:
Bot notifies a disc channel when one of its members reaches 99 in all skills

- 200M Notifier:
Bot notifies a disc channel when one of its members reaches 200M in a skill

- All 200M Notificer:
Bot notifies a disc channel when one of its members reaches 200M in all skills

- Competition Start:
Bot notifies a disc channel when a competition for that group has begun

- Competition Overtake:
Bot notifies a disc channel when the first place has been overtaken
Example: "Psikoi" was overtaken by "Elvard" which now holds the first place in the "RSPT" Competition!

- Competition Daily Stats:
Notify the channel every 24h with daily stats from the players aswell as their place in the competition
Example:
1 - "Elvard" - Gained XXXXXX experience the last 24 hours!"
2 - "Ze Punhetas" - Gained XXXXXX experience in the last 24 hours!
etc. for everyone who has > 0 exp gained throughout the competition

- Competition Final Hour:
Bot notifies a disc channel when a competition is 1 hour away from ending

- Competition End:
Bot notifies a disc channel when a competition has ended

**Comment by dariosantos6** [comment]
I would like to see something like:

!group/clan "Bloatjob"

So anyone could check what clans/groups X player is on, great tool for pvp clans for example, or even pvm/skilling.

**Comment by rui-martins** [comment]
`!groupinfo [group]`

Would retrieve group size and list its members.

**Comment by psikoi** [comment]
Closed in favor of https://github.com/wise-old-man/discord-bot/issues/2
