### ISSUE TITLE
New endpoint for split bossing and skilling data

### ISSUE THREAD

**Issue by thespragg** [wise-old-man/wise-old-man#508]
There's a high possibility I might've just missed it, but it would be great to have a player endpoint that returns with the structure:

player{
"name": "" 
..etc
"skills":[],
"bosses":[]
}

When using the api with c# its difficult to deserialize the latestSnapshot property since the structure is an object containing multiple differently structured objects, could an endpoint be added that returns the player object but without the latestSnapshot property and instead with skills and bosses as their own array

**Comment by psikoi** [comment]
This could probably be done with a certain param flag that triggers an outgoing middleware that would convert the regular response to a differently typed one, example:

```
{
  "username": "abcdef",
  "type": "ironman",
  "skills": [
    { "name": "Attack", "experience": 2183648, "rank": 74739, "ehp": 84.98942}
    ...
  ]
  "bosses": [
    { "name": "Zulrah", "kills": 32, "rank": 8474, "ehb": 3.48453}
    ...
  ]
}
```

**Comment by psikoi** [comment]
This is really old, but since v2 of the API, skills and bosses are now separate. 

https://docs.wiseoldman.net/players-api/player-endpoints#get-player-details
