### ISSUE TITLE
/groups/:id/monthly-top endpoint returns null for groups that don't exist

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#545]
Example: wiseoldman.net/api/groups/113333/monthly-top
It should probably return "Group not found.", like a few other endpoints do.

It also returns null for groups that don't have any members.

**Comment by rorro** [comment]
Notes:
When removing a player from a group, is there a way to give a non valid tracked player as input? I have tried but not succeeded. Help.

**Comment by psikoi** [comment]
This was left as it is to avoid doing one extra database fetch for endpoints that don't require it, but I agree that the fetch is worth doing in exchange for API consistency.
