### ISSUE TITLE
"Maxed combat" achievement

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#548]
When somebody achieves max combat, the website and discord bot list the achievement as "Maxed Combat", but doesn't list any contributing skills that helped to achieve maxed combat. To me, it would make sense to also announce the most recent 99(s) that completed the achievement. In the example below, 99 prayer would be announced alongside max combat.

![Screenshot_18](https://user-images.githubusercontent.com/66145237/102712402-5ee04280-427e-11eb-9048-fbbfcac9027d.png)

![Screenshot_19](https://user-images.githubusercontent.com/66145237/102712457-a797fb80-427e-11eb-9243-c3addbb2d9ee.png)

As a side note, on this person's profile, the mouse tooltip on the prayer progress bar says 99 unachieved, even though it is stated on another part of the same page that they have completed that milestone. I'm not sure if this contributes to the issue somehow.
![Screenshot_20](https://user-images.githubusercontent.com/66145237/102712552-5dfbe080-427f-11eb-8f17-b4a83e7e1ecf.png)

**Comment by psikoi** [comment]
That is to be expected, that player reached 126 combat at 98 prayer.

**Comment by psikoi** [comment]
**I guess the solution here is to rename that achievement to "126 Combat"**

**Comment by psikoi** [comment]
Fixed in #611
