### ISSUE TITLE
API: Cannot read namechange details of approved namechanges

### ISSUE THREAD

**Issue by MathieuDR** [wise-old-man/wise-old-man#561]
Hello

I'm unable to retrieve the detailed information of 'approved' namechanges in the namechange api.

Pending Example that works (as of now it is pending) `https://wiseoldman.net/api/names/1072`
Denied Example that works: `https://wiseoldman.net/api/names/1076`
Approved example that does not work `https://wiseoldman.net/api/names/1087`

Error (1087)
```json
{
    "message": "Cannot read property 'id' of null"
}
```

Besides that it is not working, the calls take extremely long (10 seconds+)

**Comment by psikoi** [comment]
It takes long because it usually makes calls to the OSRS hiscores, and that by itself is slow to respond.

I'll check this out
