### ISSUE TITLE
Error messages are inconsistent for players/[:id, username/:username]/[competitions, achievements, snapshots, gained, records, names]

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#566]
The error messages returned are different for using :id or username/:username.
If the username is not found 'Player not found' is returned, but if the id doesn't exist an empty array is returned.

For /gained a complete response is returned for id, but with all null and 0 values.

**Comment by psikoi** [comment]
Can't seem to reproduce this for some reason, do you remember how?

**Comment by rorro** [comment]
Here are examples:
https://api.wiseoldman.net/players/999999/competitions - returns [] because there is no player with the id 999999.
https://api.wiseoldman.net/players/username/oijdaoidasjoda/competitions - returns Player not found because oijdaoidasjoda doesn't exist.
