### ISSUE TITLE
Recent player achievements

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#585]
I would love the ability able to see the most recent achievements on a player's page, similar to what shows on the group page.

**Comment by Hydrox6** [comment]
So this? 
![image](https://user-images.githubusercontent.com/2979691/103487946-d1b1f780-4e00-11eb-839b-53d21897bf59.png)

**Comment by Sethmare** [comment]
I suppose so. Don’t know how I’ve always overlooked that haha. Then i guess an amendment to my suggestion would be to add it to the achievement page, and maybe add a couple more to the histort?

**Comment by psikoi** [comment]
> Then i guess an amendment to my suggestion would be to add it to the achievement page, and maybe add a couple more to the histort?

Makes sense, sure
