### ISSUE TITLE
Add name change auto approval for accounts with 200m in a skill

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#616]
By scraping this page:

`https://secure.runescape.com/m=hiscore_oldschool/overall?category_type=0&table={SKILL_INDEX}&page={CEIL(SKILL_RANK/ 25)}`

And then finding the name in the `SKILL_RANK` position, and finally comparing it to the `newName`.

**Comment by psikoi** [comment]
Can no longer be done because Jagex is now blocking website scraping. Closing.

**Comment by 0x464e** [comment]
Shouldn't this be fine for handling top 50 people in any hiscore page?  
https://secure.runescape.com/m=hiscore_oldschool/ranking.json?table=0&category=0&size=50  
Or do you get blocked here as well?

**Comment by psikoi** [comment]
It's limited to top 50, so this feature could be changed to be top 50 of every skill, instead of 200m exp, that would work.
