### ISSUE TITLE
[ui] Updated success message is a red alert

### ISSUE THREAD

**Issue by AllanOcelot** [wise-old-man/wise-old-man#654]
Good first commit for a new user maybe,

Steps to replicate:
 - Go to user page
 - Press update button
 - See red notice, notice should be green/blue for good UI 

![image](https://user-images.githubusercontent.com/11334905/106943008-c3ffd280-671c-11eb-8465-6296db8e3324.png)

**Comment by psikoi** [comment]
But that is an error message, why would it not be red?

**Comment by AllanOcelot** [comment]
Nope, you are correct, I didn't bother to read the alert apparently ahahaha!
