### ISSUE TITLE
Add the ability to track multiple skills on a comp via ehp.

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#656]
An EHP competition that only tracks specific skills, decided by the creator of the competition.

For example I might want to run an ehp competition, and allow the competitors to choose any of the gathering skills.
So someone could choose to do Mining/Fishing/Woodcutting/Hunter or any combination of them to contribute to the ehp being tracked for the competition.

**Comment by BoomOSRS** [comment]
This would also be great for PVM competitions.
i.e. Tracking selected bosses by EHB.
Groups could choose to track EHB for Bandos,Arma,Zammy & Sara for a GWD event, or all of the Slayer Bosses, or Wilderness Bosses for example.
I think this would be great if users could select which skills/bosses contribute to the EHP/EHB for their competition, rather than having preset combinations.

**Comment by psikoi** [comment]
Closing this in favor of #817
