### ISSUE TITLE
In the Gained tab, clicking on an entry in the table while the table is sorted causes the table to get unsorted, and the item now in the position you clicked to get selected

### ISSUE THREAD

**Issue by Enriath** [wise-old-man/wise-old-man#709]
To reproduce:
1. Go to a gained page (here's mine: https://wiseoldman.net/players/hydrox6/gained/skilling)
2. Sort the table in some way. I was sorting mine by exp gained.
3. Click on one of the options in the sorted table.
4. Notice that (unless you were lucky), the item you clicked on was not the graph that you're now viewing.

Here I clicked on Firemaking, but ended up on Attack, since Attack is in that position when unsorted.
![image](https://user-images.githubusercontent.com/2979691/111810270-ba49bd00-88cd-11eb-960f-85ff82af1d4c.png)
![image](https://user-images.githubusercontent.com/2979691/111810288-c0d83480-88cd-11eb-8cf1-ff86857c9cbc.png)

**Comment by psikoi** [comment]
It seems to reset the table's sorting when you select a row, weird
