### ISSUE TITLE
Import groups from CML/TempleOSRS

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#72]
Would be very nice for transitioning existing groups/clans.

**Comment by dekvall** [comment]
In the meantime i have create a simple bash script to accomplish this

You just need to specify:
 - `WOMNAME` - What your group name should be on Wise Old Man
 - `GROUPLINK` - The link to your previous group from either TempleOSRS or CML. The links can be in the formats, and must be inside the quotes (`"`):
    - https://templeosrs.com/groups/members.php?id=44
    - https://crystalmathlabs.com/tracker/virtualhiscores.php?page=statistics&group=8
```bash
WOMNAME=""; GROUPLINK="";  [ -n "$WOMNAME" ] && [ -n "$GROUPLINK" ] && curl -s "$GROUPLINK" | grep -oP 'php\?player=\K[\w\d\s]+'| jq -R -s --arg WOMNAME "$WOMNAME" 'split("\n")[:-1] | [.[] | {"username":., "role":"member"}] | {"name":$WOMNAME, "members":.}' | curl -s -H "Content-Type: application/json" -X POST -d @- https://wiseoldman.net/api/groups | jq '.verificationCode // .message' && echo "=====REMEMBER YOUR VERIFICATION CODE=====" || echo "You must provide groupname and a link to your current group!"
```

If you are on windows you can either use [Windows Subsystem for Linux](https://ubuntu.com/wsl) or a [repl](https://repl.it/languages/bash), the latter is probably easiest.

Then you just paste the command in the terminal and press run.
