### ISSUE TITLE
Modify sorting/selection for !group competitions --upcoming

### ISSUE THREAD

**Issue by Aluminoti** [wise-old-man/wise-old-man#726]
Overall details are found here https://discord.com/channels/679454777708380161/696219233167736884/829374464126353448

This issue encompasses the !group competitions --upcoming command for the discord bot.
Currently, it seems this command is grabbing the most recently created competition.

I would expect this to show me the closest upcoming competition.

**Comment by psikoi** [comment]
Related to #728  and #727

**Comment by psikoi** [comment]
This command doesn't support status parameters (--upcoming / --ongoing / --finished). 
This issue might be improved by https://github.com/wise-old-man/discord-bot/pull/87

Closing.
