### ISSUE TITLE
Modify sorting/selecting for !group competitions

### ISSUE THREAD

**Issue by Aluminoti** [wise-old-man/wise-old-man#727]
Overall details are found here https://discord.com/channels/679454777708380161/696219233167736884/829374464126353448

This issue encompasses the !group competitions command for the discord bot.
Currently, it seems this command is grabbing the top 5 most recently created competitions

I would expect this to show me the top 5 closest upcoming competition. (based on start date rather than creation date)

**Comment by psikoi** [comment]
Related to #728 #726
