### ISSUE TITLE
Mobile group view

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#745]
Currently, looking at a group member list only shows the member name and their "role" in the group:
![image](https://user-images.githubusercontent.com/66145237/115965615-452e6080-a4e7-11eb-82fb-53a7f11c0841.png)

You currently can't scroll horizontally to view more data, so all you can see is those two things unless you rotate your phone (which doesn't work if you've opened Wise Old Man through Discord.) It would be more relevant to show each member's overall xp or level in each skill instead of their role. It would also be nice if the table could be scrolled through horizontally, with the usernames staying pinned so they are always viewable.

**Comment by aleccaputo** [comment]
@psikoi i'll take this
