### ISSUE TITLE
Add boss sets in future boss competitions.

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#78]
mkbd on discord:
> When making boss tracking, can you make it so that you can group certain bosses for competitions. Like dks, wildy bosses, and gwd bosses?

**Comment by discomethod** [comment]
I think this enhancement can be generalized to adding groups of skills/bosses across the site, not just for competitions. For example, tracking my personal non-combat skill experience gained over the past week; or, tracking my group's slayer bosses killed in the past month. 

"Overall" experience is conceptually an example of such a group, but probably not implemented as a sum of all skills as it is pulled directly from Hiscores.

**Comment by psikoi** [comment]
Superseded by #601
