### ISSUE TITLE
Base X stats achievement progress incorrectly calculated

### ISSUE THREAD

**Issue by discomethod** [wise-old-man/wise-old-man#808]
The achievement partial progress towards base X stats is improperly calculated. On an account with all except 3 skills at 90+ (and those skills are 88+), the achievement progress reads "Base 90 Stats 55.22% completed". The account is probably more accurately 90%+ of the way to base 90s. Other base X achievement partial progress may also be improperly calculated, although there seems to be no issue with actually awarding the achievement when base X is reached.

**Comment by psikoi** [comment]
Ah, I see the issue, I don't exactly remember why I did this at the time, but the way the progress is being calculated is

`PROGRESS_TO_90_BASE = LOWEST_SKILL'S_EXP / EXP_AT_LVL_90`

And this causes issues if you have everything 90+ except 1 def, for example, as you should be nearly 95% (22/23) to the goal, but you'd be around 0% on the website.

I guess the right way to fix this would be to sum the exp of all skills (capped at 5.4m for lvl 90), divided by (23 * 5.4m)

**Comment by jkinequon** [comment]
I wouldn't mind taking this one. Seems easy enough.

**Comment by psikoi** [comment]
Great thanks, feel free to message me on discord if you need any help 👍

**Comment by jkinequon** [comment]
Just double checking if you want to see if it's good to merge in. Been open for a while :p

**Comment by psikoi** [comment]
> Just double checking if you want to see if it's good to merge in. Been open for a while :p

Yes I do, apologies, reviewing now.
