### ISSUE TITLE
Discord Bot - Command to preview competition summaries for other metrics

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#822]
Now it's possible to preview competitions for other metrics on the site, it would make sense to add this feature to the bot commands also.
For example if I was hosting a GWD event, I wouldn't create 4 separate competitions any more, I would create one for Bandos, and then preview it for Armadyl/Kril/Zilyana. It would be great to get the ability to preview the summaries for each on the bot too, atm it would only be possible to get the summary for Bandos.

i.e. `!group competition 2981 --arma`

**Comment by psikoi** [comment]
Moved to https://github.com/wise-old-man/discord-bot/issues/100
