### ISSUE TITLE
Make name change search case insensitive

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#842]
Currently searching the name changes is case sensitive, causing any capital letters in the search bar to pull up no results since most(if not all) usernames are currently lowercase. This should be changed to be case insensitive to show more accurate results

**Comment by aleccaputo** [comment]
Any reason we'd ever want to be case sensitive for name related thing? If not i'd probably want the query to be normalized, ie 
```
  if (username && username.length > 0) {
    query[Op.or] = [
      { oldName: { [Op.like]: `${username}%` } },
      { newName: { [Op.like]: `${username}%` } }
    ];
  }
```
Lowercase here instead of on the controller or the client. Thoughts? @Jakesterwars
