### ISSUE TITLE
Suggestion: Slowly migrate to TypeScript on the client

### ISSUE THREAD

**Issue by aleccaputo** [wise-old-man/wise-old-man#845]
Wondering what your thoughts are on slowly moving the client to Typescript?
I've done this migration a few times in the past, where the philosophy is basically "if you touch the file, attempt to migrate it to TS/TSX". 
It certainly is a decent amount of work to do the entire migration, but if you do the "slow burn" approach, you can at least make new files TS moving forward.

[TSC allows you to build with a hybrid approach](https://www.typescriptlang.org/tsconfig/#allowJs) (allowJS: true) for this specific use case/workflow. Maybe the full migration is never completed, but aside from a slightly different build toolchain, i don't see a ton of downsides.

Thoughts?

**Comment by psikoi** [comment]
I've been wanting to migrate to Next.js for a while, it would give me the flexibility to 

- server-side render some pages (which would be great for SEO and link previews)
- client-side render other pages (that wouldn't need SEO like the "search" page)
- generate static pages at build time, and revalidate them every X seconds (for pages that don't change often like the EHP/EHB rates pages)

So I suppose switching to typescript would be very possible during this migration 👍

**Comment by joey-colon** [comment]
+1 to using Next :) 

Would be interested in helping out with the migration process if this happens!

**Comment by psikoi** [comment]
> +1 to using Next :)
> 
> Would be interested in helping out with the migration process if this happens!

oh thanks :) are you on our discord?

**Comment by aleccaputo** [comment]
@psikoi you pay for this yourself, right? Might want to consider costs (money) of SSR vs CSR. Plus do those benefits outweigh the time and risks associated with that refactor? Just food for thought.
Helpful link
https://developers.google.com/web/updates/2019/02/rendering-on-the-web#wrapup

**Comment by psikoi** [comment]
@aleccaputo @joeydotdev 

This is now being built, still in beta with a few big pages missing. Built using Next.js 13.4 (App Router) and Tailwind.

https://beta.wiseoldman.net/

**Comment by psikoi** [comment]
Added in the new beta website https://beta.wiseoldman.net/

I'll consider it done as it'll eventually be live in production. Closing.
