### ISSUE TITLE
Remove Reset capitalization button from user profiles

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#853]
As this feature has been blocked from working for some time, it should just be removed from profiles.
Alternatively it could just give a response to explain that the feature does not work any more and why until we have an alternative solution for correcting name capitalization.

**Comment by Sethmare** [comment]
Potential workaround for correcting capitalization:

https://github.com/wise-old-man/discord-bot/issues/112#issue-959405193
