### ISSUE TITLE
Groups special guests

### ISSUE THREAD

**Issue by Sforrego** [wise-old-man/wise-old-man#870]
Currently i was removed from a clans group by the sync feature because i am not in the clan (it is my secondary clan).

I was thinking there could be a feature where certain people could be added a special guests and therefore not deleted from the group by the sync feature.

**Comment by psikoi** [comment]
@rorro isn't there an "ignore rank" option on the plugin? Would it solve this?

**Comment by rorro** [comment]
The ignore rank feature would do the opposite of that. It would not add the people with the ignored rank. There is however an "always included" option where one can add names that will always be added to the group no matter the sync option.
