### ISSUE TITLE
Add "info message" and link to our discord on the "Name Changes" page

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#890]

**Comment by lukaszklis** [comment]
Do we have any content specified with regards to what the message should say?

**Comment by psikoi** [comment]
“Most name changes are approved automatically within a few minutes. If a name change has a “Pending” or “Denied” status after this period, there is likely an issue with the name change that needs to be resolved in our Discord support channel.

(With a link to our discord, similar to the one in the CreateGroup page)

**Comment by psikoi** [comment]
Added in the new beta website https://beta.wiseoldman.net/

I'll consider it done as it'll eventually be live in production. Closing.
