### ISSUE TITLE
Allow multiple team panels to be opened on team competitions

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#891]
Currently on team competitions, you can open each team individually to view their individual member gains within the team standing, but you can only open one team's panel at a time.
If I'm viewing Team A, and then want to view Team B, Team A will close when I open Team B.

This doesn't allow me to open certain teams side by side to compare, but most importantly it seems a bit janky/jerky with how they open/close.
I feel it would be better if they stayed open until you closed them for each team.

See discord message for reference
https://discord.com/channels/679454777708380161/774713646382972978/889933106046464041

**Comment by psikoi** [comment]
Added in the new beta website https://beta.wiseoldman.net/

I'll consider it done as it'll eventually be live in production. Closing.
