### ISSUE TITLE
Feature: Option to hide P2P content on F2P accounts

### ISSUE THREAD

**Issue by blakegearin** [wise-old-man/wise-old-man#892]
Showing P2P skills, bosses, etc. on F2P accounts doesn't seem to provide much value.

**Comment by psikoi** [comment]
@autumn-smellegy interested?

**Comment by autumn-smellegy** [comment]
Yes! @psikoi

**Comment by devenini** [comment]
+1

**Comment by psikoi** [comment]
Implemented in #1263. Closing.

**Comment by autumn-smellegy** [comment]
Skills are now hidden, but p2p bosses and activities still show up on f2p profiles.
