### ISSUE TITLE
[BUG] Group ironman tagged as "regular"

### ISSUE THREAD

**Issue by Antimated** [wise-old-man/wise-old-man#908]
Hey, my friend made a GIM account but it is [displayed as a "regular" account on wiseoldman](https://wiseoldman.net/players/onkruijd). Reassigning player type doesn't seem to help.

**Comment by Antimated** [comment]
Might not be a bug as there is yet to be a check for group ironmans :)

**Comment by Sethmare** [comment]
We don’t currently have a Group Ironman mode, for now all GIM are being tracked as regular accounts since that is how they appear on the hiscores

**Comment by Antimated** [comment]
Oh ok I though there was a separate hiscore :) my bad!
