### ISSUE TITLE
Suggestion: Wise Old Man Dashboard

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#911]
To allow for easier group management, we could allow group leaders to access a "Dashboard" that allows them to manage their group(s) as well as the Discord bot.

**The theory:**
Anybody could create a WiseOldMan account. Group leaders can add multiple groups to their Dashboard using the verification code given on creation. After the group is added to your Dashboard, you no longer need to use the code to manage your group as long as you are signed in. Maybe an optional Discord sign in option?
The Dashboard could also have a integration with the Discord bot, allowing the group leader to add the bot to servers they own and change the bot's configurations.

**Pros:**
- Makes contacting group leaders easier
- Allows group leaders to approve applications to their groups (if that feature is added)
- Email alerts become a possibility with account creation (could be useful for being notified of applicants, etc)
- Easier group management
- Manage groups Patreon perks (tbd)

**Cons**
- Lots of work/time
- Would require significant security
- Likely to cost more to run

**Comment by psikoi** [comment]
This will require an authentication system, Discord is most likely the chosen provider. However, it's a huge undertaking and brings up some questions regarding ownership.

Let's say we introduce Discord auth and allow you to edit your groups by logging in with Discord. What happens to groups that were created and managed with a verification code?

Would you be able to "redeem" ownership with Discord by inserting your verification code? Then at some point we'd need to invaidate that code, but if there's multiple group leaders? How does permission management look like? Would you have to invite other admins?

I'll probably be revisiting this topic next year, but not anytime soon. Closing until that time comes.
