### ISSUE TITLE
Suggestion: Apply to join group/competition

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#912]
Allow users to "apply" to join a group or competition. These applications would need to be approved somehow by the person with the verification code

**Comment by llebc** [comment]
Hi @Sethmare understand this is quite dated but willing to take it on if still available and wanted?

I'm looking of doing something like the following:

- Adding an "Apply" button to the groups / competitions homepage.
- The user would then click this, a modal opens and they input there profile name.
- Adding "Applications" to the dropdown inside of the configuration for groups.
- Applications to see would require some form of authentication, this being through the use of the verification code.
- This would generate a signed JWT token for an hour whereby the user can access the "Applications" tab.
- Add middleware which could be used in future to protect the GET: /api/applications, PATCH: /api/applications DELETE: /api/applications routes.
- See applications / approve / reject through the use of the JWT token.

Let me know your thoughts and if this is still available.

**Comment by psikoi** [comment]
There's no immediate plans to implement this. Closing until that changes.
