### ISSUE TITLE
Group gains calculations timing out

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#931]
Group gains for larger groups are taking too long to calculate (times out after 60s) and eventually displays "No results found"
![image](https://user-images.githubusercontent.com/70453840/151976785-e5e6262a-83f8-46c8-a38e-84edbe80268a.png)
![image](https://user-images.githubusercontent.com/70453840/151976796-180d0944-5990-4cc7-aa36-45a8f731b051.png)

**Comment by psikoi** [comment]
Should have been fixed in #1013
