### ISSUE TITLE
Feature Suggestion: Clan Staff Verification Code

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#938]
Discord suggestion from Zyych#0001 (<@ 183275565929725953>):

“ Would it be possible to generate two verification codes for a group, one administrator code that allows the all permissions and a second moderator code that restricts access to deleting/editing the group but allows competitions and update all?”

https://discord.com/channels/679454777708380161/696219233167736884/956240834343366657

**Comment by psikoi** [comment]
There's no immediate plans to implement this. Closing until that changes.
