### ISSUE TITLE
Update-all on comps - error message refers to 1hr cooldown instead of 24hr.

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#939]
https://discord.com/channels/679454777708380161/705827679538249738/930584515754225687
As per above discord anouncement, the cooldown on update-alls on competitions should be 24hrs if not within the first or last 6hrs of the competition. If attempting to update-all on a competition when no users are oudated (updated over 24hrs ago) the error message still refers to the old 1h cooldown.

![image](https://user-images.githubusercontent.com/70453840/160459090-cea31633-e31c-48bc-9e1f-f0bbfd87fcaf.png)

**Comment by psikoi** [comment]
Fixed in #980
