### ISSUE TITLE
Bug: Players with ending values but no starting values on comps

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/wise-old-man#944]
Several players on [this competition](https://wiseoldman.net/competitions/10873/participants) have no Starting snapshot, but do have an Ending snapshot registered, which is causing their entire account's xp to be registered as gained during the competition.

[Discord #support channel discussion here](https://discord.com/channels/679454777708380161/696219355138228254/967527919176011816)

![image](https://user-images.githubusercontent.com/70453840/164948391-cd5a725e-d28c-4f19-add9-b1ad856ff269.png)
![image](https://user-images.githubusercontent.com/70453840/164948396-8f0c01b1-c009-43fd-bf91-fa2eccf37838.png)

**Comment by psikoi** [comment]
Not sure how this happened, closing this for now, will re-open if it happens again or if we find out how to reproduce.
