### ISSUE TITLE
Suggestion: Tracking Boss KC

### ISSUE THREAD

**Issue by imee3** [wise-old-man/wise-old-man#945]
Is it possible to track boss kill progression, similar to how XP gained is tracked? Currently when viewing the bossing section while looking up a character, you just see their current kill count. I would like to get it to track the gained kill count when using a specific selected date range from the filter.

**Comment by psikoi** [comment]
There is already boss and minigame/activity tracking. There's a drop-down selector on the website that changes the types of metrics displayed skilling/bossing/activities, check it out.
