### ISSUE TITLE
Afghanistan (AF) flag displaying incorrectly

### ISSUE THREAD

**Issue by ghost** [wise-old-man/wise-old-man#949]
On 15 August 2021 the Islamic Emirate of Afghanistan adopted a flag consisting of the *Shahada* oath in black script on a white field, replacing the flag used from 9 October 2004 – 15 August 2021.

The website still displays the previous iteration of the flag, and should be updated.

https://en.wikipedia.org/wiki/Flag_of_Afghanistan

**Comment by samjowen** [comment]
Hi folks, can I work on this?

**Comment by psikoi** [comment]
hello, absolutely 👍

**Comment by samjowen** [comment]
> hello, absolutely 👍

Great, thanks for the swift reply.

**Comment by samjowen** [comment]
@psikoi - Just curious where the original set of flags came from in this PR: #628. 

I am happy to make the SVG myself, with the appropriate styling too, if the new AF flag is not available anywhere.
