### ISSUE TITLE
Add ability to go to player page using URL referencing player name

### ISSUE THREAD

**Issue by dabolink** [wise-old-man/wise-old-man#96]
add an additional way of getting to the player page by using the players IGN

players/{name} wouldnt work for numerical usernames

other options:
players/rsn/{name}
players/name/{name}
players?name={name}

**Comment by dekvall** [comment]
I prefer `/players/rsn/{name}`, it's short and sweet.

**Comment by CubeLuke** [comment]
Definitely a +1 to this.

Would something like `/player/{name}` suffice? No reason for the plural and the rsn part just seems excessive since there's no other type of player-specific item to my knowledge that you would want to query.

**Comment by Jakesterwars** [comment]
What use-case would this be in? A manual URL that you can make or an additional bit of check on the /get function?

**Comment by psikoi** [comment]
Copying what I wrote on discord:

> the API already support username lookups, so it would be a UI only change

**Comment by psikoi** [comment]
This is now high priority due to a possible Runelite integration.
