### ISSUE TITLE
Issue with Group Creation via API

### ISSUE THREAD

**Issue by InfernalPlank** [wise-old-man/wise-old-man#971]
The following portion of code determines if a group is eligible to be created based on the values supplied in the request's "members" field:
https://github.com/wise-old-man/wise-old-man/blob/fcf8b022faf1497410eb919c226fecef9d14f177/server/src/api/services/internal/group.service.ts#L487-L490
However, when using the following sample code:
```py
def create_group():
    base_url = "https://api.wiseoldman.net/groups"
    group_data = {
        "name": "Cool Kids",
        "description": "Dunkin' on doofuses.",
        "clanChat": "200mOnly",
        "homeworld": 302,
        "members": [
            {
                "username": "Lynx Titan",
                "role": "leader"
            },
            {
                "username": "7asty",
                "role": "member"
            }
        ]
    }
    print(f"POSTing \"{group_data}\" to \"{base_url}\"...")
    print("Length of Members Array: " + str(len(group_data["members"])))
    totalUNs = 0
    for dictio in group_data["members"]:
        if "username" in dictio.keys():
            totalUNs += 1
    print("Number of Array Elements with Username Key: " + str(totalUNs))
    r = requests.post(base_url, data=group_data)
    response = r.json()
    print(response)
```
We get the following:
```
POSTing "{'name': 'Cool Kids', 'description': "Dunkin' on doofuses.", 'clanChat': '200mOnly', 'homeworld': 302, 'members': [{'username': 'Lynx Titan', 'role': 'leader'}, {'username': '7asty', 'role': 'member'}]}" to "https://api.wiseoldman.net/groups"...
Length of Members Array: 2
Number of Array Elements with Username Key: 2
{'message': 'Invalid members list. Each array element must have a username key.'}
```
As you can see, the criteria in the API itself is being met (length of members = number of members elements with "username" field), yet the error is being thrown anyways. Is this a known issue, or am I doing something wrong?

Thanks.

**Comment by psikoi** [comment]
Hey, I've just tried sending this same request, with the same payload, through a REST API client (Insomnia) and I couldn't reproduce this error 🤔 

Is that python? I did a quick google on `requests.post` https://www.w3schools.com/PYTHON/ref_requests_post.asp

could you try `json=group_data` instead?

**Comment by InfernalPlank** [comment]
Hey, thanks for the quick reply and sorry for my late response! I had written this issue later in the evening and had gone to sleep shortly after. It appears I was sleep deprived as I had overlooked the `data=` and `json=` issue completely! That indeed was the fix. Thanks for the help!
